inherits: ..\\languages-formats.yml

dimensions:
- alias: product
  values: [java]
- alias:  operation
  values: [image]
- alias:  url
  values: [extract-image]
- alias:  fileformat
  values: [docx, pptx, xlsx, pdf, odt, ods, odp, epub, fb2]

generationRules:
  include:
  - fileformat[docx, pptx, xlsx, pdf, odt, ods, odp, epub, fb2]
  
outputPath: "parser\\{product}\\{url}\\{fileformat}.{lang}.md"

dictionaries: [ ..\\..\\data\\products.json ]
