inherits: ..\\products.yml

dimensions:  
- alias: ext
  values: ["excel", "image", "onenote", "visio", "web", "word", "worksheet", "chm", "csv", "doc", "docm", "docx", "dot", "dotm", "dotx", "eml", "emlx", "epub", "fb2", "md", "mhtml", "msg", "odp", "ods", "odt", "one", "ost", "otp", "ots", "ott", "pdf", "pot", "potx", "pps", "ppsm", "ppsx", "ppt", "pptm", "pptx", "pst", "rtf", "txt", "xhtml", "xla", "xlam", "xls", "xlsx", "xlsb", "xlsm", "xlsm", "xlt", "xltm", "xltx", "xml"]

generationRules:
  exclude:
    - ext[excel, image, onenote, visio, web, word, worksheet]
  include:
##  - ext[odt]

dictionaries: [ "..\\..\\data\\hyperlink\\{product}.{lang}.json", "..\\..\\data\\hyperlink\\{product}.json", "..\\..\\data\\otherformats.json" ]

outputPath: "{product}\\extract\\hyperlink\\{ext}.{lang}.md"