inherits: ..\\products.yml

dimensions: 
- alias: ext
  values: ["excel", "image", "onenote", "visio", "web", "word", "worksheet", "doc", "docm", "docx", "dot", "dotm", "dotx", "odp", "ods", "odt", "otp", "ots", "ott", "pdf", "pot", "potx", "pps", "ppsm", "ppsx", "ppt", "pptm", "pptx", "rtf", "xlam", "xls", "xlsx", "xlsb", "xlsm", "xlsm", "xlt", "xltm", "xltx"]


generationRules:
  exclude:
    - ext[excel, image, onenote, visio, web, word, worksheet]
  include:
##  - ext[odt]

dictionaries: [ "..\\..\\data\\parse\\{product}.{lang}.json", "..\\..\\data\\parse\\{product}.json", "..\\..\\data\\otherformats_parse.json" ]

outputPath: "{product}\\parse\\{ext}.{lang}.md"